### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by drizk1** [TidierOrg/TidierDB.jl#2]
Hey @pdimens ! Hope you're well. TidierDB is moving along and transferring over to tidier soon. When you have some time, we'd love to get your magic icon touch. 

Thank you!

**Comment by pdimens** [comment]
Maybe a bit lighter
![image](https://github.com/TidierOrg/TidierDB.jl/assets/19176506/23a58aaf-0b4a-4856-a1d8-faf637d49359)

**Comment by kdpsingh** [comment]
Love it @pdimens! I kind of prefer the darker color to differentiate it more from the TidierVest logo color.

It's your call, @drizk1.

**Comment by drizk1** [comment]
Let's do the darker! I love the richness of the purple
