### ISSUE TITLE
How can I write functions that pass arguments do TidierDB functions?

### ISSUE THREAD

**Issue by vituri** [TidierOrg/TidierDB.jl#20]
Example: I want to write a function `f` that filter some data in my database. However, I don't want to fix the columns that can be filtered. 

How can I create something like the following:

```
function f(con, conditions)
    @chain begin
        DB.db_table(con, :My_table)
        DB.@filter(conditions)
        .....................
        DB.@collect
    end
end
```
?

If I try something like `f(con, Id == 1)` I get the error `UndefVarError: `Id` not defined` which arises from Julia trying to evaluate my expression. Is there some workaround?

**Comment by drizk1** [comment]
To do those, you need to use bang bang interpolation and pass what you need as strings. 

```
function f(con, conditions)
   add_interp_parameter!(:conditions, :conditions)
    @chain begin
        db_table(con, :My_table)
        @filter(!!conditions)
        @show_query
    end
end

f(con, "Id == 1")
```
```
WITH cte_1 AS (
SELECT *
        FROM My_table
        WHERE Id = 1)  
SELECT *
        FROM cte_1
```

**Comment by drizk1** [comment]
So, unfortunately, the way interpolatio is currently set up, you cannot write a function (run time/ compile time issue i think I hope to one day get rid of.)

You can however use a macro to get around this. 

```
macro f(con, conditions, columns)
    add_interp_parameter!(:conditions, conditions)
    add_interp_parameter!(:columns, columns)

   return quote
    @chain db_table(con, :My_table) begin
        @filter(!!conditions)
        @select !!columns 
        @show_query
    end
    end
end 
```
```
@f(con, "ID > 0", "column_test")
```
```
```
SELECT *
        FROM My_table
        WHERE ID > 0)  
SELECT column_test
        FROM cte_1
```
```
@f(con, "ID > 1000", name)
```
```
WITH cte_1 AS (
SELECT *
        FROM My_table
        WHERE ID > 1000)  
SELECT name
        FROM cte_1
```

**Comment by kdpsingh** [comment]
This is a great workaround. Agree this should eventually be fixable.

**Comment by drizk1** [comment]
I have been tinkering with the TidierData's `parse_interpolation` to try to see if I can get a version of it to fit without any luck quite yet. 

For now, I will add brief documentation page on this since it's functional and others may find it useful, but leave this issue open.

**Comment by drizk1** [comment]
@vituri I found a fully functional work around that will let you update the values and interpolate into filter statements.

I wrote a macro called `@interpolate` (for now with source code below) that properly escapes and allows you to change values and interpolate.I am not fully sure why this works (i think it some brings the scopes onto the same level @kdpsingh probably know) but it lets you build a macro that so that you can pass arguments to TidierDB chains. Unfortunately TidierDB mixes strings and so it needs access to the expression contents before it begins the quote, which means without a big rewrite this will be the most graceful method for now, I think.

arguments are `con` which I plan to remove and as many tuples of what you want to interpolate `(:var_name, var_value)` 

Of note: you _**cannot**_ chain `@interpolate` and your macro together.

When you have a moment, try this out to see if it works for you. If so I will add docs and can release it.

```
using Pkg; Pkg.add(url = "https://github.com/TidierOrg/TidierDB.jl#broaden-interpolation-ability")
using TidierDB
con = connect(:duckdb);

macro my_chain(con, conditions, columns)
    return quote
        @chain db_table(con, :My_table) begin
        @filter(Day in [!!conditions])
        @select(!!columns)
        @show_query
       end
    end
end 

col_names = [:mpg, :gas, :wt]
dates = ["2024-12-10", "2024-12-5"]
@interpolate(con, (:conditions, dates), (:columns, col_names));
@my_chain(con, dates, col_names)
```
```
WITH cte_1 AS (
SELECT *
        FROM My_table
        WHERE Day in ('2024-12-10', '2024-12-5'))  
SELECT mpg, gas, wt
        FROM cte_1
```
```
col_names = [:cyl, :model, :gear]
weeks = ["WEEK 1", "WEEK 2"]
@interpolate(con, (:conditions, weeks), (:columns, col_names));
@my_chain(con, weeks, col_names)
```
```
WITH cte_1 AS (
SELECT *
        FROM My_table
        WHERE Day in ('WEEK 1', 'WEEK 2'))  
SELECT cyl, model, gear
        FROM cte_1
```


here is the source code in case you are curious.
```
macro interpolate(con, args...)
    exprs = Expr[]
    for arg in args
        if !(arg isa Expr && arg.head == :tuple)
            throw(ArgumentError("Each argument must be a tuple"))
        end
        name, value = arg.args
        push!(exprs, :(esc(add_interp_parameter!(Symbol($name), $((value))))))
    end
    return esc(Expr(:block, exprs...))
end
```

**Comment by vituri** [comment]
Because my mind can't understand all this black-magic metaprogramming, I was trying to manipulate the SQL string that is outputed by `finalize_query` and substitute the vectors "manually" by the corresponding "IN (v1, v2, ..., vn)".

I tried your solution and it works fine outside a function. But what if I want something like that:

```
macro bd_eventos(con, dias)
    return quote
        @chain db_table(con, :Resumo_frota) begin
        TidierDB.@filter(Day in [!!dias])
        TidierDB.@show_query
       end
    end
end

function bd_eventos(con, dias)
    @interpolate(con, (:dias, dias));

    res = @bd_eventos(con, dias)

    res
end

dias = ["2024-01-04"]
bd_eventos(con, dias)
```

When should I use `@interpolate(con, (:dias, dias))`? Inside a function it does not work.

**Comment by drizk1** [comment]
using the the `@eval` interpolation method, it is now quite straight forward to interpolate into TidierDB chains.  may actually be able to finally close this issue once i update the docs... 
```
function test(vals)
       @eval @chain DB.t(test_db) begin
           DB.@filter(value in $vals)
           DB.@collect
       end
end
vals = [1,  2,  3, 4]
other_vals = [1]
test(vals)
8×4 DataFrame
 Row │ id      groups  value  percent 
     │ String  String  Int64  Float64 
─────┼────────────────────────────────
   1 │ AA      bb          1      0.1
   2 │ AF      aa          1      0.6
   3 │ AB      aa          2      0.2
   4 │ AG      bb          2      0.7
   5 │ AC      bb          3      0.3
   6 │ AH      aa          3      0.8
   7 │ AD      aa          4      0.4
   8 │ AI      bb          4      0.9
test(other_vals)
2×4 DataFrame
 Row │ id      groups  value  percent 
     │ String  String  Int64  Float64 
─────┼────────────────────────────────
   1 │ AA      bb          1      0.1
   2 │ AF      aa          1      0.6
```

**Comment by drizk1** [comment]
Going to close this for now that I've added some brief [docs](https://tidierorg.github.io/TidierDB.jl/latest/examples/generated/UserGuide/functions_pass_to_DB/#write-pipeline-function-to-use-inside-of-chains) around it. Plz reopen/reach out as things come up
