### ISSUE TITLE
Documenter is a useless dependency

### ISSUE THREAD

**Issue by giordano** [TidierOrg/TidierDB.jl#40]
I don't have the time to make a PR, but [Documenter isn't used in the code of this package](https://github.com/search?q=repo%3ATidierOrg%2FTidierDB.jl+Documenter+path%3A%2F%5Esrc%5C%2F%2F&type=code), so it shouldn't be a direct dependency.

**Comment by drizk1** [comment]
Thank you so much for catching this. 

I will fix this soon.
