### ISSUE TITLE
Add example for how to connect to a local duckdb database

### ISSUE THREAD

**Issue by kdheepak** [TidierOrg/TidierDB.jl#64]
I'm not able to figure out how to connect to an existing file:

<img width="550" alt="image" src="https://github.com/user-attachments/assets/947469ea-5433-4bf8-856a-ca44d0ababfb">

I'm assuming this functionality exists but I don't see it in the documentation.

**Comment by kdheepak** [comment]
This works:

<img width="430" alt="image" src="https://github.com/user-attachments/assets/d62858e2-be3c-4000-8856-d5d2c95e6431">

It requires the name of the file to end with `.duckdb`:

https://github.com/TidierOrg/TidierDB.jl/blob/d6651eb59f7123f122c29e0163a93444bf69a7ab/src/TidierDB.jl#L413-L421

**Comment by drizk1** [comment]
Hey thanks for reaching out. It absolutely can be improved.  

I'll have this fixed soon. Plz let me know if anything else comes up.

**Comment by drizk1** [comment]
I added a brach ("enhance-windowframe") you can try that where `connect` should now support a `.duck.db` file 

I will have to look into allowing `db_table` to support a database file as it does not right now, and i will definitely clarify the docs around it.

**Comment by kdheepak** [comment]
The docs have code like this:

```
path_or_name = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

@chain DB.db_table(db, path_or_name) begin
```

Which made me think a local path would work but that doesn't appear to be the case.

**Comment by drizk1** [comment]
Ahh yes I should clarify in the docs that only supports file paths no db paths

**Comment by drizk1** [comment]
I have added example to the docs [getting started page](https://tidierorg.github.io/TidierDB.jl/latest/examples/generated/UserGuide/getting_started/#connect-to-a-local-database-file) 

Please reopen this issue or open any new issues if anything comes up.
