### ISSUE TITLE
BigQuery connection for location != US

### ISSUE THREAD

**Issue by ErwanPiR** [TidierOrg/TidierDB.jl#71]
Hi,

I was trying to use TidierDB.jl to connect to a private BigQuery database and I had an error due to the hardcoded location in the collect_gbq() and get_table_metadata() function of GBQExt.jl file (line 50 and line 89) : 

```
    query_data = Dict(
    "query" => query,
    "useLegacySql" => false,
    "location" => "US")
```

In order to support other locations (EU, us-west1,...) provider by GCP, the location should be a parameter of this function so the user can specify the location of his database. Another way is to delete this part since it works without, but not sure if it's good practice...

Thanks

**Comment by drizk1** [comment]
Hi thanks for bringing this up. 

Have you confirmed it works without it ? 

If so, I may opt to use that for the time being. 

Either way I'll release a new version that should work for you in the next day or so

**Comment by ErwanPiR** [comment]
Well, I haven't done a ton of test but yes, it works for me for different locations if you just don't specify the location 🙂 !


________________________________
De : Daniel Rizk ***@***.***>
Envoyé : lundi 7 octobre 2024 18:20
À : TidierOrg/TidierDB.jl ***@***.***>
Cc : Erwan Pierre ***@***.***>; Author ***@***.***>
Objet : Re: [TidierOrg/TidierDB.jl] BigQuery connection for location != US (Issue #71)


Hi thanks for bringing this up.

Have you confirmed it works without it ?

If so, I may opt to use that for the time being.

Either way I'll release a new version that should work for you in the next day or so

**Comment by drizk1** [comment]
I changed the GBQ connection to work as follows so that the all underlying function have access to the user specified location. I also improved type mapping when collecting to a dataframe.
```
conn = connect(gbq(), "json_cred_path", "location") 
```
Before releasing the next version, I have to polish up a few things, but you are welcome to try out the updated version by installing with this line and then if anything else comes up, please do let me know.
```
using Pkg; Pkg.add(url = "https://github.com/TidierOrg/TidierDB.jl", rev = "catch-a-bug-then-write-a-test")
```

**Comment by drizk1** [comment]
This should now be fixed in v.5.0 which is heading to the registry, please reopen this issue/start a new one if there continues to be an issue or I can do anything else to improve the GBQ backend
