### ISSUE TITLE
Unable to read parquet file using DuckDB

### ISSUE THREAD

**Issue by kdheepak** [TidierOrg/TidierDB.jl#84]
I'm able to read a parquet file using DuckDB from the DuckDB command line interface:

![image](https://github.com/user-attachments/assets/d3b592cc-c97d-451a-ac6c-a67e1be17a76)

But when I try the same thing with TidierDB, I get an error:

<img width="730" alt="image" src="https://github.com/user-attachments/assets/f216881c-9c43-41f6-bb47-c04b35252ceb">

Any idea what might be going on here?

**Comment by drizk1** [comment]
Hmm not totally sure. 

Do you mind sharing what version you are using? 

Also try using the following string inside `db_table` for your table name

`"read
_parquet('./power-infra-usa geoparquet')"`

**Comment by kdheepak** [comment]
I was able to do this to make it work using the duckdb function directly:

```
db = DB.connect(DB.duckdb())

usa_power_infra = DB.db_table(db, "read_parquet('power-infra-usa.geoparquet')");
```

**Comment by kdheepak** [comment]
We commented at the same time :)

**Comment by drizk1** [comment]
Love it! As always if anything else comes up or there are any feature or improvements you'd like please let me know.  

Grouping directly in mutate and summarize is available in a branch I will be releasing soon.
