### ISSUE TITLE
After an error with the DuckDB backend, TidierDB is unable to proceed even when fixing the error

### ISSUE THREAD

**Issue by kdheepak** [TidierOrg/TidierDB.jl#86]
I have code that works:

<img width="550" alt="image" src="https://github.com/user-attachments/assets/0f75a519-4cbf-4854-bffa-5562438d5926">

But when I cause an error:

<img width="730" alt="image" src="https://github.com/user-attachments/assets/284bd9ab-4032-40dc-80a8-07f10542229a">

And after causing an error when I revert back to the code that works, it still continues to fail with the same old error:

<img width="760" alt="image" src="https://github.com/user-attachments/assets/a169266a-c240-4aff-bfdf-a57865cb5bdb">

Here's a video of that in action:

https://github.com/user-attachments/assets/198720d1-6d77-4674-b59b-abc8d819ff99

It continues to work if I recreate the connection and table.

**Comment by drizk1** [comment]
So as far as the table goes comedies are stored as mutable structs. 

So after you save the table, you need to use t(table_name) starting to change. Otherwise you will alter the underlying struct. 

Resave the table and then as long as you refer to it with `DB.t(table)` this should fix this issue

**Comment by kdheepak** [comment]
That resolves this thank you!
